name = "tailwind-do"
#route = { pattern = "*/*", zone_name = "tailwind.do" }
main = "dist/index.mjs"
usage_model = "unbound"
compatibility_date = "2022-09-23"
logpush = true

services = [
    { binding = "CTX", service = "ctx-do", environment = "production" }
]

[build]
command = "npm run build"

[build.upload]
format = "modules"

[miniflare]
durable_objects_persist = "./data/"  
kv_persist = "./data/" 

[miniflare.mounts]
ctx-do = "../ctx.do"